#!/bin/bash
# Install/Update Script for Server API for Cimitra
# Author: Tay Kratzer tay@cimitra.com
# GitHub Location: https://github.com/cimitrasoftware/nix-api-modules

declare SOFTWARE_TITLE="Cimitra API Modules Module"
declare DEFAULT_INSTALL_PATH="/var/opt/cimitra/api/modules"
declare INSTALL_PATH="/var/opt/cimitra/api/modules"

echo ""
echo "Process: Installing ${SOFTWARE_TITLE}"
mkdir -p ${INSTALL_PATH} 2> /dev/null

declare -i INSTALL_PATH_EXISTS=`test -d ${INSTALL_PATH} ; echo $?`

if [ $INSTALL_PATH_EXISTS -ne 0 ]
then
echo ""
echo "Error: Cannot Access Installation Path: ${INSTALL_PATH}"
echo ""
exit 1
fi
 
cd ${INSTALL_PATH} 2> /dev/null

RESULT=`echo $?` 

if [ $RESULT -ne 0 ]
then
echo ""
echo "Error: Cannot Access Installation Path: ${INSTALL_PATH}"
echo ""
exit 1
fi

{
curl -LJO https://raw.githubusercontent.com/cimitrasoftware/nix-api-server/master/modules
} 1> /dev/null 2>/dev/null
chmod +x ./modules



echo ""
echo "Success: Installing ${SOFTWARE_TITLE}"

echo ""
echo "Module help: cimitra modules"
echo ""
echo "-or-"
echo ""
echo "/var/opt/cimitra/api/modules/modules"
echo ""